# Generated by Django 4.0.2 on 2022-02-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoros', '0002_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(to='phoros.tags'),
        ),
    ]
