# Generated by Django 4.0.2 on 2022-02-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoros', '0003_image_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
